services:
  app:
    image: ghcr.io/iamcooller/life-rpg:latest
    container_name: life-rpg
    ports:
      - "3333:3000"
    env_file:
      - .env.production
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
